/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CommentCreateNestedManyWithoutVideosInput } from "./CommentCreateNestedManyWithoutVideosInput";
import { ValidateNested, IsOptional, IsInt, IsString } from "class-validator";
import { Type } from "class-transformer";
import { LikeCreateNestedManyWithoutVideosInput } from "./LikeCreateNestedManyWithoutVideosInput";

@InputType()
class VideoCreateInput {
  @ApiProperty({
    required: false,
    type: () => CommentCreateNestedManyWithoutVideosInput,
  })
  @ValidateNested()
  @Type(() => CommentCreateNestedManyWithoutVideosInput)
  @IsOptional()
  @Field(() => CommentCreateNestedManyWithoutVideosInput, {
    nullable: true,
  })
  comments?: CommentCreateNestedManyWithoutVideosInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  commentsCount?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  createdBy?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => LikeCreateNestedManyWithoutVideosInput,
  })
  @ValidateNested()
  @Type(() => LikeCreateNestedManyWithoutVideosInput)
  @IsOptional()
  @Field(() => LikeCreateNestedManyWithoutVideosInput, {
    nullable: true,
  })
  likes?: LikeCreateNestedManyWithoutVideosInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  likesCount?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  thumbnail?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  url?: string | null;
}

export { VideoCreateInput as VideoCreateInput };
